/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazConFuncionalidad;

import java.awt.Color;
import java.text.DecimalFormat;

/**
 *
 * @author Marcos Flores Barbero
 */
public class SumandoNumeros extends javax.swing.JFrame {

    /**
     * Creates new form SumandoNumeros
     */
    public SumandoNumeros() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSumando = new javax.swing.JPanel();
        jLabelNumero1 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jButtonSumar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jTextFieldSumando1 = new javax.swing.JTextField();
        jTextFieldSumando2 = new javax.swing.JTextField();
        jTextFieldResultado = new javax.swing.JTextField();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sumando numeros");

        jPanelSumando.setBorder(javax.swing.BorderFactory.createTitledBorder("Sumando"));
        jPanelSumando.setToolTipText("");

        jLabelNumero1.setText("Primer numero");

        jLabelNumero2.setText("Segundo numero");

        jLabelResultado.setText("Resultado");
        jLabelResultado.setEnabled(false);

        jButtonSumar.setText("Sumar");
        jButtonSumar.setEnabled(false);
        jButtonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonBorrarMouseExited(evt);
            }
        });
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jTextFieldSumando1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSumando1KeyReleased(evt);
            }
        });

        jTextFieldSumando2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSumando2KeyReleased(evt);
            }
        });

        jTextFieldResultado.setEnabled(false);

        javax.swing.GroupLayout jPanelSumandoLayout = new javax.swing.GroupLayout(jPanelSumando);
        jPanelSumando.setLayout(jPanelSumandoLayout);
        jPanelSumandoLayout.setHorizontalGroup(
            jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSumandoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSumar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBorrar)
                .addGap(69, 69, 69))
            .addGroup(jPanelSumandoLayout.createSequentialGroup()
                .addGroup(jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldSumando2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSumandoLayout.createSequentialGroup()
                        .addGroup(jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSumandoLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabelNumero2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSumandoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelResultado, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNumero1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSumandoLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSumandoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSumando1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanelSumandoLayout.setVerticalGroup(
            jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSumandoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero1)
                    .addComponent(jTextFieldSumando1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumero2)
                    .addComponent(jTextFieldSumando2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResultado)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSumandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSumar)
                    .addComponent(jButtonBorrar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(56, 56, 56))
            .addComponent(jPanelSumando, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSumando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalir)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSumando2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSumando2KeyReleased
        boolean esNumero1 = false, esNumero2 = false;
        try {
            String s1 = jTextFieldSumando1.getText();
            String s2 = jTextFieldSumando2.getText();
            String replace1 = s1.replace(',', '.');
            String replace2 = s2.replace(',', '.');
            Float.parseFloat(replace1);
            esNumero1 = true;
            Float.parseFloat(replace2);
            esNumero2 = true;
        } catch (NumberFormatException excepcion) {
            esNumero1 = false;
            esNumero2 = false;
        }
        if (jTextFieldSumando1.getText().length() > 0 && jTextFieldSumando2.getText().length() > 0 && esNumero1 && esNumero2) {
            jButtonSumar.setEnabled(true);
        } else {
            jButtonSumar.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldSumando2KeyReleased

    private void jButtonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumarActionPerformed
        DecimalFormat df = new DecimalFormat(".##");
        String s1 = jTextFieldSumando1.getText();
        String s2 = jTextFieldSumando2.getText();
        String replace1 = s1.replace(',', '.');
        String replace2 = s2.replace(',', '.');
        Float resultado = (Float.parseFloat(replace1)) + (Float.parseFloat(replace2));
        String res = df.format(resultado);
        jTextFieldResultado.setText(res);
    }//GEN-LAST:event_jButtonSumarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldSumando1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSumando1KeyReleased
        boolean esNumero1 = false, esNumero2 = false;
        try {
            String s1 = jTextFieldSumando1.getText();
            String s2 = jTextFieldSumando2.getText();
            String replace1 = s1.replace(',', '.');
            String replace2 = s2.replace(',', '.');
            Float.parseFloat(replace1);
            esNumero1 = true;
            Float.parseFloat(replace2);
            esNumero2 = true;
        } catch (NumberFormatException excepcion) {
            esNumero1 = false;
            esNumero2 = false;
        }
        if (jTextFieldSumando1.getText().length() > 0 && jTextFieldSumando2.getText().length() > 0 && esNumero1 && esNumero2) {
            jButtonSumar.setEnabled(true);
        } else {
            jButtonSumar.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldSumando1KeyReleased

    private void jButtonBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrarMouseEntered
        jButtonBorrar.setBackground(Color.yellow);
    }//GEN-LAST:event_jButtonBorrarMouseEntered

    private void jButtonBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBorrarMouseExited
        jButtonBorrar.setBackground(null);
    }//GEN-LAST:event_jButtonBorrarMouseExited

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        jTextFieldSumando1.setText("");
        jTextFieldSumando2.setText("");
        jTextFieldResultado.setText("");
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        jButtonSalir.setBackground(Color.CYAN);
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        jButtonSalir.setBackground(null);
    }//GEN-LAST:event_jButtonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumandoNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumandoNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumandoNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumandoNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SumandoNumeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSumar;
    private javax.swing.JLabel jLabelNumero1;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JPanel jPanelSumando;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldSumando1;
    private javax.swing.JTextField jTextFieldSumando2;
    // End of variables declaration//GEN-END:variables
}
