/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empleados;

import javax.swing.DefaultListModel;
import javax.swing.*;

/**
 *
 * @author Marcos Flores Barbero
 */
public class JList extends javax.swing.JFrame {

    /**
     * Creates new form JList
     */
    public JList() {
        initComponents();
         jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);
        jListEmpleados.setModel(Empleado.modeloLista);
        Empleado E1 = new JefeDeProyectos("Pedro", "García", 1205, 5);
        Empleado E2 = new JefeDeProyectos("Raúl", "Pérez", 1150, 4);
        Empleado E3 = new JefeDeProyectos("David", "Bermejo", 1300, 7);
        Empleado E4 = new Montador("Pedro", "García", 15, 75);
        Empleado E5 = new Montador("Raúl", "Pérez", 5, 55);
        Empleado E6 = new Montador("David", "Bermejo", 13, 78);
        Empleado E7 = new TrabajadorPorHoras("Pedro", "García", 8, 10);
        Empleado E8 = new TrabajadorPorHoras("Raúl", "Pérez", 5, 5.5);
        Empleado E9 = new TrabajadorPorHoras("David", "Bermejo", 10, 8.5);
        Empleado E10 = new Vendedor("Pedro", "García", 8, 10, 1200);
        Empleado E11 = new Vendedor("Raúl", "Pérez", 4, 20.5, 1000);
        Empleado E12 = new Vendedor("David", "Bermejo", 10, 18.5, 950);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroupGrupo = new javax.swing.ButtonGroup();
        jPanelDatosTrabajador = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelMetodo1 = new javax.swing.JLabel();
        jLabelMetodo2 = new javax.swing.JLabel();
        jLabelMetodo3 = new javax.swing.JLabel();
        jTextFieldMetodo1 = new javax.swing.JTextField();
        jTextFieldMetodo2 = new javax.swing.JTextField();
        jTextFieldMetodo3 = new javax.swing.JTextField();
        jPanelTipoTrabajadores = new javax.swing.JPanel();
        jPanelTipoTrabajador = new javax.swing.JPanel();
        jRadioButtonJefeDeProyecto = new javax.swing.JRadioButton();
        jRadioButtonTrabajadorPorHoras = new javax.swing.JRadioButton();
        jRadioButtonTrabajadorMontador = new javax.swing.JRadioButton();
        jRadioButtonTrabajadorVendedor = new javax.swing.JRadioButton();
        jButtonAñadir = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList();
        jLabelSeleccioneTrabajador = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jButtonBorrarEmpleado = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuTrabajador = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenu();
        jMenuItemJefePro = new javax.swing.JMenuItem();
        jMenuItemTraPorH = new javax.swing.JMenuItem();
        jMenuItemTraMont = new javax.swing.JMenuItem();
        jMenuItemVendedor = new javax.swing.JMenuItem();
        jMenuItemBorrarTodos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDatosTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Trabajador"));
        jPanelDatosTrabajador.setToolTipText("");

        jLabelNombre.setText("Nombre: ");

        jLabelApellido.setText("Apellido:");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabelMetodo1.setText("jLabel1");

        jLabelMetodo2.setText("jLabel2");

        jLabelMetodo3.setText("jLabel3");

        jTextFieldMetodo1.setText("jTextField1");

        jTextFieldMetodo2.setText("jTextField1");

        jTextFieldMetodo3.setText("jTextField1");

        javax.swing.GroupLayout jPanelDatosTrabajadorLayout = new javax.swing.GroupLayout(jPanelDatosTrabajador);
        jPanelDatosTrabajador.setLayout(jPanelDatosTrabajadorLayout);
        jPanelDatosTrabajadorLayout.setHorizontalGroup(
            jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosTrabajadorLayout.createSequentialGroup()
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMetodo3)
                    .addComponent(jLabelApellido)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelMetodo1)
                    .addComponent(jLabelMetodo2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMetodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMetodo3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );
        jPanelDatosTrabajadorLayout.setVerticalGroup(
            jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosTrabajadorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMetodo1)
                    .addComponent(jTextFieldMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMetodo2)
                    .addComponent(jTextFieldMetodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMetodo3)
                    .addComponent(jTextFieldMetodo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTipoTrabajadores.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos trabajadores"));

        jPanelTipoTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo trabajador"));

        buttonGroupGrupo.add(jRadioButtonJefeDeProyecto);
        jRadioButtonJefeDeProyecto.setText("Jefe de proyecto");
        jRadioButtonJefeDeProyecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonJefeDeProyectoItemStateChanged(evt);
            }
        });

        buttonGroupGrupo.add(jRadioButtonTrabajadorPorHoras);
        jRadioButtonTrabajadorPorHoras.setText("Trabajador por horas");
        jRadioButtonTrabajadorPorHoras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTrabajadorPorHorasItemStateChanged(evt);
            }
        });

        buttonGroupGrupo.add(jRadioButtonTrabajadorMontador);
        jRadioButtonTrabajadorMontador.setText("Trabajador Montador");
        jRadioButtonTrabajadorMontador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTrabajadorMontadorItemStateChanged(evt);
            }
        });

        buttonGroupGrupo.add(jRadioButtonTrabajadorVendedor);
        jRadioButtonTrabajadorVendedor.setText("Trabajador vendedor");
        jRadioButtonTrabajadorVendedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTrabajadorVendedorItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipoTrabajadorLayout = new javax.swing.GroupLayout(jPanelTipoTrabajador);
        jPanelTipoTrabajador.setLayout(jPanelTipoTrabajadorLayout);
        jPanelTipoTrabajadorLayout.setHorizontalGroup(
            jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonJefeDeProyecto)
                    .addComponent(jRadioButtonTrabajadorPorHoras)
                    .addComponent(jRadioButtonTrabajadorVendedor)
                    .addComponent(jRadioButtonTrabajadorMontador))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        jPanelTipoTrabajadorLayout.setVerticalGroup(
            jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonJefeDeProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrabajadorPorHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrabajadorMontador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrabajadorVendedor)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButtonAñadir.setText("Añadir");
        jButtonAñadir.setEnabled(false);
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");

        javax.swing.GroupLayout jPanelTipoTrabajadoresLayout = new javax.swing.GroupLayout(jPanelTipoTrabajadores);
        jPanelTipoTrabajadores.setLayout(jPanelTipoTrabajadoresLayout);
        jPanelTipoTrabajadoresLayout.setHorizontalGroup(
            jPanelTipoTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTipoTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTipoTrabajadoresLayout.createSequentialGroup()
                        .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelTipoTrabajadoresLayout.createSequentialGroup()
                        .addComponent(jPanelTipoTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelTipoTrabajadoresLayout.setVerticalGroup(
            jPanelTipoTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadoresLayout.createSequentialGroup()
                .addComponent(jPanelTipoTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTipoTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trabajadores en activo"));

        jListEmpleados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEmpleadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListEmpleados);

        jLabelSeleccioneTrabajador.setText("Seleccione un trabajador para ver su salario ");

        jLabelSalario.setText("Salario");

        jTextFieldSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalarioActionPerformed(evt);
            }
        });

        jButtonBorrarEmpleado.setText("Eliminar Trabajador");
        jButtonBorrarEmpleado.setEnabled(false);
        jButtonBorrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSeleccioneTrabajador)
                    .addComponent(jLabelSalario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonBorrarEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(jTextFieldSalario, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSeleccioneTrabajador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBorrarEmpleado)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuArchivo.setText("Archivo");
        jMenuBar.add(jMenuArchivo);

        jMenuTrabajador.setText("Trabajador");

        jMenuNuevo.setText("Nuevo");

        jMenuItemJefePro.setText("Jefe de Proyecto");
        jMenuNuevo.add(jMenuItemJefePro);

        jMenuItemTraPorH.setText("Trbajador por horas");
        jMenuNuevo.add(jMenuItemTraPorH);

        jMenuItemTraMont.setText("Trabajador montador");
        jMenuNuevo.add(jMenuItemTraMont);

        jMenuItemVendedor.setText("Trabajador vendedor");
        jMenuNuevo.add(jMenuItemVendedor);

        jMenuTrabajador.add(jMenuNuevo);

        jMenuItemBorrarTodos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBorrarTodos.setText("Borrar todos");
        jMenuTrabajador.add(jMenuItemBorrarTodos);

        jMenuBar.add(jMenuTrabajador);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDatosTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTipoTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTipoTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jTextFieldSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalarioActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jListEmpleadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEmpleadosValueChanged
       jButtonBorrarEmpleado.setEnabled(true);
       Empleado emp = (Empleado)jListEmpleados.getSelectedValue();
       jTextFieldSalario.setText(Double.toString(emp.salario()));
    }//GEN-LAST:event_jListEmpleadosValueChanged

    private void jButtonBorrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarEmpleadoActionPerformed
        jButtonBorrarEmpleado.setEnabled(false);
        jListEmpleados.remove(jListEmpleados.getSelectedIndex());
        Empleado.modeloLista.remove(jListEmpleados.getSelectedIndex());
        
       
    }//GEN-LAST:event_jButtonBorrarEmpleadoActionPerformed

    private void jRadioButtonJefeDeProyectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonJefeDeProyectoItemStateChanged
        //Deshabilito los 6 campos por defecto
        jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);
        
        //Habilito los necesarios para este boton
        jLabelMetodo1.setVisible(true);
        jLabelMetodo1.setText("Salario base:");
        
        jLabelMetodo2.setVisible(true);
        jLabelMetodo2.setText("Numero proyectos:");

        jTextFieldMetodo1.setVisible(true);
        jTextFieldMetodo1.setText("");
        
        jTextFieldMetodo2.setVisible(true);
        jTextFieldMetodo2.setText("");
                
    }//GEN-LAST:event_jRadioButtonJefeDeProyectoItemStateChanged

    private void jRadioButtonTrabajadorPorHorasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTrabajadorPorHorasItemStateChanged
        //Deshabilito los 6 campos por defecto
        jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);
        
        //Habilito los necesarios para este boton
        jLabelMetodo1.setVisible(true);
        jLabelMetodo1.setText("Numero de horas trabajadas:");
        
        jLabelMetodo2.setVisible(true);
        jLabelMetodo2.setText("Salario por hora:");
        
        jTextFieldMetodo1.setVisible(true);
        jTextFieldMetodo1.setText("");
        
        jTextFieldMetodo2.setVisible(true);
        jTextFieldMetodo2.setText("");
        
        
    }//GEN-LAST:event_jRadioButtonTrabajadorPorHorasItemStateChanged

    private void jRadioButtonTrabajadorMontadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTrabajadorMontadorItemStateChanged
       //Deshabilito los 6 campos por defecto
        jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);
        
        //Habilito los necesarios para este boton
        jLabelMetodo1.setVisible(true);
        jLabelMetodo1.setText("Numero de electrodomesticos:");
        
        jLabelMetodo2.setVisible(true);
        jLabelMetodo2.setText("Importe por unidad:");
                
        jTextFieldMetodo1.setVisible(true);
        jTextFieldMetodo1.setText("");
        
        jTextFieldMetodo2.setVisible(true);
        jTextFieldMetodo2.setText("");
    }//GEN-LAST:event_jRadioButtonTrabajadorMontadorItemStateChanged

    private void jRadioButtonTrabajadorVendedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTrabajadorVendedorItemStateChanged
        //Deshabilito los 6 campos por defecto
        jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);
        
        //Habilito los necesarios para este boton
        jLabelMetodo1.setVisible(true);
        jLabelMetodo1.setText("Electrodomesticos vendidos:");
        
        jLabelMetodo2.setVisible(true);
        jLabelMetodo2.setText("Comision:");
        
        jLabelMetodo3.setVisible(true);
        jLabelMetodo3.setText("Salario base:");
        
        jTextFieldMetodo1.setVisible(true);
        jTextFieldMetodo1.setText("");
        
        jTextFieldMetodo2.setVisible(true);
        jTextFieldMetodo2.setText("");
        
        jTextFieldMetodo3.setVisible(true);
        jTextFieldMetodo3.setText("");
    }//GEN-LAST:event_jRadioButtonTrabajadorVendedorItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGrupo;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBorrarEmpleado;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelMetodo1;
    private javax.swing.JLabel jLabelMetodo2;
    private javax.swing.JLabel jLabelMetodo3;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSeleccioneTrabajador;
    private javax.swing.JList jListEmpleados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemBorrarTodos;
    private javax.swing.JMenuItem jMenuItemJefePro;
    private javax.swing.JMenuItem jMenuItemTraMont;
    private javax.swing.JMenuItem jMenuItemTraPorH;
    private javax.swing.JMenuItem jMenuItemVendedor;
    private javax.swing.JMenu jMenuNuevo;
    private javax.swing.JMenu jMenuTrabajador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDatosTrabajador;
    private javax.swing.JPanel jPanelTipoTrabajador;
    private javax.swing.JPanel jPanelTipoTrabajadores;
    private javax.swing.JRadioButton jRadioButtonJefeDeProyecto;
    private javax.swing.JRadioButton jRadioButtonTrabajadorMontador;
    private javax.swing.JRadioButton jRadioButtonTrabajadorPorHoras;
    private javax.swing.JRadioButton jRadioButtonTrabajadorVendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldMetodo1;
    private javax.swing.JTextField jTextFieldMetodo2;
    private javax.swing.JTextField jTextFieldMetodo3;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables
}
