/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Empleados;

import javax.swing.DefaultListModel;
import javax.swing.*;

/**
 *
 * @author Marcos Flores Barbero
 */
public class JList extends javax.swing.JFrame {

    static boolean flag = false;

    /**
     * Creates new form JList
     */
    public JList() {
        initComponents();
        jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);
        jListEmpleados.setModel(Empleado.modeloLista);
        Empleado E1 = new JefeDeProyectos("Pedro", "García", 1205, 5);
        Empleado E2 = new JefeDeProyectos("Raúl", "Pérez", 1150, 4);
        Empleado E3 = new JefeDeProyectos("David", "Bermejo", 1300, 7);
        Empleado E4 = new Montador("Pedro", "García", 15, 75);
        Empleado E5 = new Montador("Raúl", "Pérez", 5, 55);
        Empleado E6 = new Montador("David", "Bermejo", 13, 78);
        Empleado E7 = new TrabajadorPorHoras("Pedro", "García", 8, 10);
        Empleado E8 = new TrabajadorPorHoras("Raúl", "Pérez", 5, 5.5);
        Empleado E9 = new TrabajadorPorHoras("David", "Bermejo", 10, 8.5);
        Empleado E10 = new Vendedor("Pedro", "García", 8, 10, 1200);
        Empleado E11 = new Vendedor("Raúl", "Pérez", 4, 20.5, 1000);
        Empleado E12 = new Vendedor("David", "Bermejo", 10, 18.5, 950);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroupGrupo = new javax.swing.ButtonGroup();
        jPanelDatosTrabajador = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelMetodo1 = new javax.swing.JLabel();
        jLabelMetodo2 = new javax.swing.JLabel();
        jLabelMetodo3 = new javax.swing.JLabel();
        jTextFieldMetodo1 = new javax.swing.JTextField();
        jTextFieldMetodo2 = new javax.swing.JTextField();
        jTextFieldMetodo3 = new javax.swing.JTextField();
        jPanelTipoTrabajadores = new javax.swing.JPanel();
        jPanelTipoTrabajador = new javax.swing.JPanel();
        jRadioButtonJefeDeProyecto = new javax.swing.JRadioButton();
        jRadioButtonTrabajadorPorHoras = new javax.swing.JRadioButton();
        jRadioButtonTrabajadorMontador = new javax.swing.JRadioButton();
        jRadioButtonTrabajadorVendedor = new javax.swing.JRadioButton();
        jButtonAñadir = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList();
        jLabelSeleccioneTrabajador = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jButtonBorrarEmpleado = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuTrabajador = new javax.swing.JMenu();
        jMenuNuevo = new javax.swing.JMenu();
        jMenuItemJefePro = new javax.swing.JMenuItem();
        jMenuItemTraPorH = new javax.swing.JMenuItem();
        jMenuItemTraMont = new javax.swing.JMenuItem();
        jMenuItemVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBorrarTodos = new javax.swing.JMenuItem();
        jMenuItemBorrarSeleccionado = new javax.swing.JMenuItem();
        jMenuItemBorrarSeleccion = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDatosTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Trabajador"));
        jPanelDatosTrabajador.setToolTipText("");

        jLabelNombre.setText("Nombre: ");

        jLabelApellido.setText("Apellido:");

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
        });

        jTextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoKeyReleased(evt);
            }
        });

        jLabelMetodo1.setText("jLabel1");

        jLabelMetodo2.setText("jLabel2");

        jLabelMetodo3.setText("jLabel3");

        jTextFieldMetodo1.setText("jTextField1");
        jTextFieldMetodo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMetodo1KeyReleased(evt);
            }
        });

        jTextFieldMetodo2.setText("jTextField1");
        jTextFieldMetodo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMetodo2KeyReleased(evt);
            }
        });

        jTextFieldMetodo3.setText("jTextField1");
        jTextFieldMetodo3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMetodo3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosTrabajadorLayout = new javax.swing.GroupLayout(jPanelDatosTrabajador);
        jPanelDatosTrabajador.setLayout(jPanelDatosTrabajadorLayout);
        jPanelDatosTrabajadorLayout.setHorizontalGroup(
            jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMetodo3)
                    .addComponent(jLabelApellido)
                    .addComponent(jLabelMetodo1)
                    .addComponent(jLabelMetodo2)
                    .addComponent(jLabelNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMetodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMetodo3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(258, 258, 258))
        );
        jPanelDatosTrabajadorLayout.setVerticalGroup(
            jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosTrabajadorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMetodo1)
                    .addComponent(jTextFieldMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMetodo2)
                    .addComponent(jTextFieldMetodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMetodo3)
                    .addComponent(jTextFieldMetodo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTipoTrabajadores.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipos trabajadores"));

        jPanelTipoTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo trabajador"));

        buttonGroupGrupo.add(jRadioButtonJefeDeProyecto);
        jRadioButtonJefeDeProyecto.setText("Jefe de proyecto");
        jRadioButtonJefeDeProyecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonJefeDeProyectoItemStateChanged(evt);
            }
        });

        buttonGroupGrupo.add(jRadioButtonTrabajadorPorHoras);
        jRadioButtonTrabajadorPorHoras.setText("Trabajador por horas");
        jRadioButtonTrabajadorPorHoras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTrabajadorPorHorasItemStateChanged(evt);
            }
        });

        buttonGroupGrupo.add(jRadioButtonTrabajadorMontador);
        jRadioButtonTrabajadorMontador.setText("Trabajador Montador");
        jRadioButtonTrabajadorMontador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTrabajadorMontadorItemStateChanged(evt);
            }
        });

        buttonGroupGrupo.add(jRadioButtonTrabajadorVendedor);
        jRadioButtonTrabajadorVendedor.setText("Trabajador vendedor");
        jRadioButtonTrabajadorVendedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTrabajadorVendedorItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipoTrabajadorLayout = new javax.swing.GroupLayout(jPanelTipoTrabajador);
        jPanelTipoTrabajador.setLayout(jPanelTipoTrabajadorLayout);
        jPanelTipoTrabajadorLayout.setHorizontalGroup(
            jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonJefeDeProyecto)
                    .addComponent(jRadioButtonTrabajadorPorHoras)
                    .addComponent(jRadioButtonTrabajadorVendedor)
                    .addComponent(jRadioButtonTrabajadorMontador))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanelTipoTrabajadorLayout.setVerticalGroup(
            jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonJefeDeProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrabajadorPorHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrabajadorMontador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTrabajadorVendedor)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButtonAñadir.setText("Añadir");
        jButtonAñadir.setEnabled(false);
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipoTrabajadoresLayout = new javax.swing.GroupLayout(jPanelTipoTrabajadores);
        jPanelTipoTrabajadores.setLayout(jPanelTipoTrabajadoresLayout);
        jPanelTipoTrabajadoresLayout.setHorizontalGroup(
            jPanelTipoTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTipoTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTipoTrabajadoresLayout.createSequentialGroup()
                        .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelTipoTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTipoTrabajadoresLayout.setVerticalGroup(
            jPanelTipoTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadoresLayout.createSequentialGroup()
                .addComponent(jPanelTipoTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTipoTrabajadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Trabajadores en activo"));

        jListEmpleados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEmpleadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListEmpleados);

        jLabelSeleccioneTrabajador.setText("Seleccione un trabajador para ver su salario ");

        jLabelSalario.setText("Salario");

        jButtonBorrarEmpleado.setText("Eliminar Trabajador");
        jButtonBorrarEmpleado.setEnabled(false);
        jButtonBorrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSeleccioneTrabajador)
                    .addComponent(jLabelSalario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonBorrarEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(jTextFieldSalario, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSeleccioneTrabajador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBorrarEmpleado)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuArchivo.setText("Archivo");
        jMenuBar.add(jMenuArchivo);

        jMenuTrabajador.setText("Trabajador");

        jMenuNuevo.setText("Nuevo");

        jMenuItemJefePro.setText("Jefe de Proyecto");
        jMenuItemJefePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJefeProActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemJefePro);

        jMenuItemTraPorH.setText("Trbajador por horas");
        jMenuItemTraPorH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraPorHActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemTraPorH);

        jMenuItemTraMont.setText("Trabajador montador");
        jMenuItemTraMont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraMontActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemTraMont);

        jMenuItemVendedor.setText("Trabajador vendedor");
        jMenuItemVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendedorActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemVendedor);

        jMenuTrabajador.add(jMenuNuevo);
        jMenuTrabajador.add(jSeparator1);

        jMenuItemBorrarTodos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBorrarTodos.setText("Borrar todos");
        jMenuItemBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarTodosActionPerformed(evt);
            }
        });
        jMenuTrabajador.add(jMenuItemBorrarTodos);

        jMenuItemBorrarSeleccionado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBorrarSeleccionado.setText("Borrar seleccionado");
        jMenuItemBorrarSeleccionado.setEnabled(false);
        jMenuItemBorrarSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarSeleccionadoActionPerformed(evt);
            }
        });
        jMenuTrabajador.add(jMenuItemBorrarSeleccionado);

        jMenuItemBorrarSeleccion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBorrarSeleccion.setText("Borrar seleccion");
        jMenuItemBorrarSeleccion.setEnabled(false);
        jMenuItemBorrarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarSeleccionActionPerformed(evt);
            }
        });
        jMenuTrabajador.add(jMenuItemBorrarSeleccion);

        jMenuBar.add(jMenuTrabajador);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelDatosTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTipoTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTipoTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        String nombre = jTextFieldNombre.getText();
        String ape = jTextFieldApellido.getText();

        if (jRadioButtonJefeDeProyecto.isSelected()) {
            double salarioB = Double.parseDouble(jTextFieldMetodo1.getText());
            double numPro = Double.parseDouble(jTextFieldMetodo2.getText());
            Empleado emp = (Empleado) new JefeDeProyectos(nombre, ape, salarioB, (int) numPro);
        }
        if (jRadioButtonTrabajadorPorHoras.isSelected()) {
            double numHoras = Double.parseDouble(jTextFieldMetodo1.getText());
            double salHora = Double.parseDouble(jTextFieldMetodo2.getText());
            Empleado emp = (Empleado) new TrabajadorPorHoras(nombre, ape, (int) numHoras, salHora);
        }
        if (jRadioButtonTrabajadorMontador.isSelected()) {
            double numElec = Double.parseDouble(jTextFieldMetodo1.getText());
            double impUni = Double.parseDouble(jTextFieldMetodo2.getText());
            Empleado emp = (Empleado) new Montador(nombre, ape, (int) numElec, impUni);
        }
        if (jRadioButtonTrabajadorVendedor.isSelected()) {
            double elecVen = Double.parseDouble(jTextFieldMetodo1.getText());
            double comision = Double.parseDouble(jTextFieldMetodo2.getText());
            double salB = Double.parseDouble(jTextFieldMetodo3.getText());
            Empleado emp = (Empleado) new Vendedor(nombre, ape, (int) elecVen, comision, salB);
        }
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jListEmpleadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEmpleadosValueChanged
        Empleado emp = (Empleado) jListEmpleados.getSelectedValue();
        jMenuItemBorrarSeleccion.setEnabled(true);
        jMenuItemBorrarSeleccionado.setEnabled(true);
        if (flag) {
            jTextFieldSalario.setText(Double.toString(emp.salario()));
        }
        flag = true;
        jButtonBorrarEmpleado.setEnabled(true);
    }//GEN-LAST:event_jListEmpleadosValueChanged

    private void jButtonBorrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarEmpleadoActionPerformed
        flag = false;
        Empleado.modeloLista.remove((int) jListEmpleados.getSelectedIndex());
        jTextFieldSalario.setText("");
        jButtonBorrarEmpleado.setEnabled(false);
        jMenuItemBorrarSeleccion.setEnabled(false);
        jMenuItemBorrarSeleccionado.setEnabled(false);


    }//GEN-LAST:event_jButtonBorrarEmpleadoActionPerformed

    private void jRadioButtonJefeDeProyectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonJefeDeProyectoItemStateChanged
        //Deshabilito los 6 campos por defecto
        jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);

        //Habilito los necesarios para este boton
        jLabelMetodo1.setVisible(true);
        jLabelMetodo1.setText("Salario base:");

        jLabelMetodo2.setVisible(true);
        jLabelMetodo2.setText("Numero proyectos:");

        jTextFieldMetodo1.setVisible(true);
        jTextFieldMetodo1.setText("");

        jTextFieldMetodo2.setVisible(true);
        jTextFieldMetodo2.setText("");

    }//GEN-LAST:event_jRadioButtonJefeDeProyectoItemStateChanged

    private void jRadioButtonTrabajadorPorHorasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTrabajadorPorHorasItemStateChanged
        //Deshabilito los 6 campos por defecto
        jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);

        //Habilito los necesarios para este boton
        jLabelMetodo1.setVisible(true);
        jLabelMetodo1.setText("Numero de horas trabajadas:");

        jLabelMetodo2.setVisible(true);
        jLabelMetodo2.setText("Salario por hora:");

        jTextFieldMetodo1.setVisible(true);
        jTextFieldMetodo1.setText("");

        jTextFieldMetodo2.setVisible(true);
        jTextFieldMetodo2.setText("");


    }//GEN-LAST:event_jRadioButtonTrabajadorPorHorasItemStateChanged

    private void jRadioButtonTrabajadorMontadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTrabajadorMontadorItemStateChanged
        //Deshabilito los 6 campos por defecto
        jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);

        //Habilito los necesarios para este boton
        jLabelMetodo1.setVisible(true);
        jLabelMetodo1.setText("Numero de electrodomesticos:");

        jLabelMetodo2.setVisible(true);
        jLabelMetodo2.setText("Importe por unidad:");

        jTextFieldMetodo1.setVisible(true);
        jTextFieldMetodo1.setText("");

        jTextFieldMetodo2.setVisible(true);
        jTextFieldMetodo2.setText("");
    }//GEN-LAST:event_jRadioButtonTrabajadorMontadorItemStateChanged

    private void jRadioButtonTrabajadorVendedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTrabajadorVendedorItemStateChanged
        //Deshabilito los 6 campos por defecto
        jLabelMetodo1.setVisible(false);
        jLabelMetodo2.setVisible(false);
        jLabelMetodo3.setVisible(false);
        jTextFieldMetodo1.setVisible(false);
        jTextFieldMetodo2.setVisible(false);
        jTextFieldMetodo3.setVisible(false);

        //Habilito los necesarios para este boton
        jLabelMetodo1.setVisible(true);
        jLabelMetodo1.setText("Electrodomesticos vendidos:");

        jLabelMetodo2.setVisible(true);
        jLabelMetodo2.setText("Comision:");

        jLabelMetodo3.setVisible(true);
        jLabelMetodo3.setText("Salario base:");

        jTextFieldMetodo1.setVisible(true);
        jTextFieldMetodo1.setText("");

        jTextFieldMetodo2.setVisible(true);
        jTextFieldMetodo2.setText("");

        jTextFieldMetodo3.setVisible(true);
        jTextFieldMetodo3.setText("");
    }//GEN-LAST:event_jRadioButtonTrabajadorVendedorItemStateChanged

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldMetodo1.setText("");
        jTextFieldMetodo2.setText("");
        jTextFieldMetodo3.setText("");
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        boolean esNumero;
        if (jTextFieldNombre.getText().length() > 0) {
            if (jTextFieldApellido.getText().length() > 0) {
                try {
                    Double.parseDouble(jTextFieldMetodo1.getText());
                    esNumero = true;
                } catch (NumberFormatException excepcion) {
                    esNumero = false;
                }
                if (jTextFieldMetodo1.getText().length() > 0 && esNumero) {
                    try {
                        Double.parseDouble(jTextFieldMetodo2.getText());
                        esNumero = true;
                    } catch (NumberFormatException excepcion) {
                        esNumero = false;
                    }
                    if (jTextFieldMetodo2.getText().length() > 0 && esNumero) {
                        if (jRadioButtonTrabajadorVendedor.isSelected()) {
                            try {
                                Double.parseDouble(jTextFieldMetodo3.getText());
                                esNumero = true;
                            } catch (NumberFormatException excepcion) {
                                esNumero = false;
                            }
                            if (jTextFieldMetodo3.getText().length() > 0 && esNumero) {
                                jButtonAñadir.setEnabled(true);
                            } else {
                                jButtonAñadir.setEnabled(false);
                            }
                        } else {
                            jButtonAñadir.setEnabled(true);
                        }
                    } else {
                        jButtonAñadir.setEnabled(false);
                    }
                } else {
                    jButtonAñadir.setEnabled(false);
                }
            } else {
                jButtonAñadir.setEnabled(false);
            }
        } else {
            jButtonAñadir.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jTextFieldApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoKeyReleased
        boolean esNumero;
        if (jTextFieldNombre.getText().length() > 0) {
            if (jTextFieldApellido.getText().length() > 0) {
                try {
                    Double.parseDouble(jTextFieldMetodo1.getText());
                    esNumero = true;
                } catch (NumberFormatException excepcion) {
                    esNumero = false;
                }
                if (jTextFieldMetodo1.getText().length() > 0 && esNumero) {
                    try {
                        Double.parseDouble(jTextFieldMetodo2.getText());
                        esNumero = true;
                    } catch (NumberFormatException excepcion) {
                        esNumero = false;
                    }
                    if (jTextFieldMetodo2.getText().length() > 0 && esNumero) {

                        if (jRadioButtonTrabajadorVendedor.isSelected()) {
                            try {
                                Double.parseDouble(jTextFieldMetodo3.getText());
                                esNumero = true;
                            } catch (NumberFormatException excepcion) {
                                esNumero = false;
                            }
                            if (jTextFieldMetodo3.getText().length() > 0 && esNumero) {
                                jButtonAñadir.setEnabled(true);
                            } else {
                                jButtonAñadir.setEnabled(false);
                            }
                        } else {
                            jButtonAñadir.setEnabled(true);
                        }
                    } else {
                        jButtonAñadir.setEnabled(false);
                    }
                } else {
                    jButtonAñadir.setEnabled(false);
                }
            } else {
                jButtonAñadir.setEnabled(false);
            }
        } else {
            jButtonAñadir.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldApellidoKeyReleased

    private void jTextFieldMetodo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMetodo1KeyReleased
        boolean esNumero;
        if (jTextFieldNombre.getText().length() > 0) {
            if (jTextFieldApellido.getText().length() > 0) {
                try {
                    Double.parseDouble(jTextFieldMetodo1.getText());
                    esNumero = true;
                } catch (NumberFormatException excepcion) {
                    esNumero = false;
                }
                if (jTextFieldMetodo1.getText().length() > 0 && esNumero) {
                    try {
                        Double.parseDouble(jTextFieldMetodo2.getText());
                        esNumero = true;
                    } catch (NumberFormatException excepcion) {
                        esNumero = false;
                    }
                    if (jTextFieldMetodo2.getText().length() > 0 && esNumero) {
                        if (jRadioButtonTrabajadorVendedor.isSelected()) {
                            try {
                                Double.parseDouble(jTextFieldMetodo3.getText());
                                esNumero = true;
                            } catch (NumberFormatException excepcion) {
                                esNumero = false;
                            }
                            if (jTextFieldMetodo3.getText().length() > 0 && esNumero) {
                                jButtonAñadir.setEnabled(true);
                            } else {
                                jButtonAñadir.setEnabled(false);
                            }
                        } else {
                            jButtonAñadir.setEnabled(true);
                        }
                    } else {
                        jButtonAñadir.setEnabled(false);
                    }
                } else {
                    jButtonAñadir.setEnabled(false);
                }
            } else {
                jButtonAñadir.setEnabled(false);
            }
        } else {
            jButtonAñadir.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldMetodo1KeyReleased

    private void jTextFieldMetodo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMetodo2KeyReleased
        boolean esNumero;
        if (jTextFieldNombre.getText().length() > 0) {
            if (jTextFieldApellido.getText().length() > 0) {
                try {
                    Double.parseDouble(jTextFieldMetodo1.getText());
                    esNumero = true;
                } catch (NumberFormatException excepcion) {
                    esNumero = false;
                }
                if (jTextFieldMetodo1.getText().length() > 0 && esNumero) {
                    try {
                        Double.parseDouble(jTextFieldMetodo2.getText());
                        esNumero = true;
                    } catch (NumberFormatException excepcion) {
                        esNumero = false;
                    }
                    if (jTextFieldMetodo2.getText().length() > 0 && esNumero) {
                        if (jRadioButtonTrabajadorVendedor.isSelected()) {
                            try {
                                Double.parseDouble(jTextFieldMetodo3.getText());
                                esNumero = true;
                            } catch (NumberFormatException excepcion) {
                                esNumero = false;
                            }
                            if (jTextFieldMetodo3.getText().length() > 0 && esNumero) {
                                jButtonAñadir.setEnabled(true);
                            } else {
                                jButtonAñadir.setEnabled(false);
                            }
                        } else {
                            jButtonAñadir.setEnabled(true);
                        }
                    } else {
                        jButtonAñadir.setEnabled(false);
                    }
                } else {
                    jButtonAñadir.setEnabled(false);
                }
            } else {
                jButtonAñadir.setEnabled(false);
            }
        } else {
            jButtonAñadir.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldMetodo2KeyReleased

    private void jTextFieldMetodo3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMetodo3KeyReleased
        boolean esNumero;
        if (jRadioButtonTrabajadorVendedor.isSelected()) {
            if (jTextFieldNombre.getText().length() > 0) {
                if (jTextFieldApellido.getText().length() > 0) {
                    try {
                        Double.parseDouble(jTextFieldMetodo1.getText());
                        esNumero = true;
                    } catch (NumberFormatException excepcion) {
                        esNumero = false;
                    }
                    if (jTextFieldMetodo1.getText().length() > 0 && esNumero) {
                        try {
                            Double.parseDouble(jTextFieldMetodo2.getText());
                            esNumero = true;
                        } catch (NumberFormatException excepcion) {
                            esNumero = false;
                        }
                        if (jTextFieldMetodo2.getText().length() > 0 && esNumero) {
                            if (jRadioButtonTrabajadorVendedor.isSelected()) {
                                try {
                                    Double.parseDouble(jTextFieldMetodo3.getText());
                                    esNumero = true;
                                } catch (NumberFormatException excepcion) {
                                    esNumero = false;
                                }
                                if (jTextFieldMetodo3.getText().length() > 0 && esNumero) {
                                    jButtonAñadir.setEnabled(true);
                                } else {
                                    jButtonAñadir.setEnabled(false);
                                }
                            } else {
                                jButtonAñadir.setEnabled(true);
                            }
                        } else {
                            jButtonAñadir.setEnabled(false);
                        }
                    } else {
                        jButtonAñadir.setEnabled(false);
                    }
                } else {
                    jButtonAñadir.setEnabled(false);
                }
            } else {
                jButtonAñadir.setEnabled(false);
            }
        } else {
            if (jTextFieldNombre.getText().length() > 0) {
                if (jTextFieldApellido.getText().length() > 0) {
                    try {
                        Double.parseDouble(jTextFieldMetodo1.getText());
                        esNumero = true;
                    } catch (NumberFormatException excepcion) {
                        esNumero = false;
                    }
                    if (jTextFieldMetodo1.getText().length() > 0 && esNumero) {
                        try {
                            Double.parseDouble(jTextFieldMetodo2.getText());
                            esNumero = true;
                        } catch (NumberFormatException excepcion) {
                            esNumero = false;
                        }
                        if (jTextFieldMetodo2.getText().length() > 0 && esNumero) {
                            if (jRadioButtonTrabajadorVendedor.isSelected()) {
                                try {
                                    Double.parseDouble(jTextFieldMetodo3.getText());
                                    esNumero = true;
                                } catch (NumberFormatException excepcion) {
                                    esNumero = false;
                                }
                                if (jTextFieldMetodo3.getText().length() > 0 && esNumero) {
                                    jButtonAñadir.setEnabled(true);
                                } else {
                                    jButtonAñadir.setEnabled(false);
                                }
                            } else {
                                jButtonAñadir.setEnabled(true);
                            }
                        } else {
                            jButtonAñadir.setEnabled(false);
                        }
                    } else {
                        jButtonAñadir.setEnabled(false);
                    }
                } else {
                    jButtonAñadir.setEnabled(false);
                }
            } else {
                jButtonAñadir.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jTextFieldMetodo3KeyReleased

    private void jMenuItemBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarTodosActionPerformed
        Empleado.modeloLista.clear();
        jMenuItemBorrarSeleccion.setEnabled(false);
        jMenuItemBorrarSeleccionado.setEnabled(false);
    }//GEN-LAST:event_jMenuItemBorrarTodosActionPerformed

    private void jMenuItemBorrarSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarSeleccionadoActionPerformed
        flag = false;
        Empleado.modeloLista.remove((int) jListEmpleados.getSelectedIndex());
        jTextFieldSalario.setText("");
        jMenuItemBorrarSeleccion.setEnabled(false);
        jMenuItemBorrarSeleccionado.setEnabled(false);
    }//GEN-LAST:event_jMenuItemBorrarSeleccionadoActionPerformed

    private void jMenuItemBorrarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarSeleccionActionPerformed
        flag = false;
        int[] seleccion = new int[jListEmpleados.getSelectedIndices().length];
        for (int i = 0; i < seleccion.length; i++) {
            Empleado.modeloLista.remove(i);
        }
        jTextFieldSalario.setText("");
        jMenuItemBorrarSeleccion.setEnabled(false);
        jMenuItemBorrarSeleccionado.setEnabled(false);
    }//GEN-LAST:event_jMenuItemBorrarSeleccionActionPerformed

    private void jMenuItemJefeProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJefeProActionPerformed
        jRadioButtonJefeDeProyecto.setSelected(true);
    }//GEN-LAST:event_jMenuItemJefeProActionPerformed

    private void jMenuItemTraPorHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraPorHActionPerformed
        jRadioButtonTrabajadorPorHoras.setSelected(true);
    }//GEN-LAST:event_jMenuItemTraPorHActionPerformed

    private void jMenuItemTraMontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraMontActionPerformed
        jRadioButtonTrabajadorMontador.setSelected(true);
    }//GEN-LAST:event_jMenuItemTraMontActionPerformed

    private void jMenuItemVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendedorActionPerformed
        jRadioButtonTrabajadorVendedor.setSelected(true);
    }//GEN-LAST:event_jMenuItemVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGrupo;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBorrarEmpleado;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelMetodo1;
    private javax.swing.JLabel jLabelMetodo2;
    private javax.swing.JLabel jLabelMetodo3;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelSeleccioneTrabajador;
    private javax.swing.JList jListEmpleados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemBorrarSeleccion;
    private javax.swing.JMenuItem jMenuItemBorrarSeleccionado;
    private javax.swing.JMenuItem jMenuItemBorrarTodos;
    private javax.swing.JMenuItem jMenuItemJefePro;
    private javax.swing.JMenuItem jMenuItemTraMont;
    private javax.swing.JMenuItem jMenuItemTraPorH;
    private javax.swing.JMenuItem jMenuItemVendedor;
    private javax.swing.JMenu jMenuNuevo;
    private javax.swing.JMenu jMenuTrabajador;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDatosTrabajador;
    private javax.swing.JPanel jPanelTipoTrabajador;
    private javax.swing.JPanel jPanelTipoTrabajadores;
    private javax.swing.JRadioButton jRadioButtonJefeDeProyecto;
    private javax.swing.JRadioButton jRadioButtonTrabajadorMontador;
    private javax.swing.JRadioButton jRadioButtonTrabajadorPorHoras;
    private javax.swing.JRadioButton jRadioButtonTrabajadorVendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldMetodo1;
    private javax.swing.JTextField jTextFieldMetodo2;
    private javax.swing.JTextField jTextFieldMetodo3;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables
}
